apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ include "grafana-gateway.name" . }}
spec:
  parentRefs:
    - name: {{ .Values.gatewayName }}
      namespace: gateway
      sectionName: https
  hostnames:
    - "{{ .Values.hostname }}"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: "{{ .Values.grafanaServiceName }}"
          port: 80
